spark:
  app_name: Glue job trading pipeline
  version: "1.0.0"
  schema_version: 1

  configs:
    spark.sql.caseSensitive: true
    spark.serializer: "org.apache.spark.serializer.KryoSerializer"

paths:
  root: "file:///D:/Projects/trading-analitical-module_new/spark_jobs" # add s3 bucket path
  sample_data: "/data/sample_data.jsonl"

  bronze:
    base: "/bronze"
    checkpoint: "/bronze/_checkpoint"
  
  silver:
    orders: "/silver/orders"
    account: "/silver/account"
    checkpoint: "/silver/_checkpoint"

  gold:
    daily_metrics: "/gold/daily_metrics"
    trades: "/gold/trades"

# Quarantine for bad records
  quarantine:
    base: "/quarantine"
